apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-fvtt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-fvtt
    app.kubernetes.io/part-of: tkrw-pr712-0075-0047-app
  name: devfile-sample-fvtt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-fvtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-fvtt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-fvtt@sha256:8b5a9602d3412875bba615f4a10939f49cbb28c9eff8ad5083f287027b0ba265
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
